name: Publish on Gradle Plugin Portal
on:
  release:
    types: [published]
jobs:
  run-gradle:
    runs-on: ubuntu-latest
    name: Run Gradle
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Run Gradle
        uses: gradle/gradle-build-action@v2
        id: publish
        env:
          GRADLE_PUBLISH_KEY: ${{secrets.GRADLE_PUBLISH_KEY}}
          GRADLE_PUBLISH_SECRET: ${{secrets.GRADLE_PUBLISH_SECRET}}
        with:
          gradle-version: 7.6
          arguments: publishPlugins
