name: Publish on Gradle Plugin Portal
on: [ release ]
jobs:
  run-gradle:
    runs-on: ubuntu-latest
    name: Run Gradle
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java-jdk
        with:
          distribution: 'adopt'
          version: 16
      - uses: actions/gradle-command-action@v1
        env:
          GRADLE_PUBLISH_KEY: ${{secrets.GRADLE_PUBLISH_KEY}}
          GRADLE_PUBLISH_SECRET: ${{secrets.GRADLE_PUBLISH_SECRET}}
        with:
          arguments: publishPlugins
