name: Publish on Gradle Plugin Portal
on:
  release:
    types: [published]
jobs:
  run-gradle:
    runs-on: ubuntu-latest
    name: Run Gradle
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
      - uses: gradle/gradle-build-action@v1
        env:
          GRADLE_PUBLISH_KEY: ${{secrets.GRADLE_PUBLISH_KEY}}
          GRADLE_PUBLISH_SECRET: ${{secrets.GRADLE_PUBLISH_SECRET}}
        with:
          build-root-directory: plugins
          arguments: publishPlugins
