name: Test plugins
on: [ push ]
jobs:
  run-gradle:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        java-version: [ 8, 11 ]
        gradle-version: [ 6.9, 7.1.1, current ]
    name: ${{ matrix.os }}, Java ${{ matrix.java-version }}, Gradle ${{ matrix.gradle-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}

      # Docker tests
      - name: Docker CLI test
        uses: gradle/gradle-build-action@v1
        id: docker-cli
        env:
          CONTAINER_REGISTRY_IMAGE_PREFIX: ${{secrets.CONTAINER_REGISTRY_IMAGE_PREFIX}}
          CONTAINER_REGISTRY_SECRET: ${{secrets.CONTAINER_REGISTRY_SECRET}}
          CONTAINER_REGISTRY_URL: ${{secrets.CONTAINER_REGISTRY_URL}}
          CONTAINER_REGISTRY_USERNAME: ${{secrets.CONTAINER_REGISTRY_USERNAME}}
        with:
          arguments: dockerPush
          gradle-version: ${{ matrix.gradle-version }}
      - name: Publish 'Docker CLI test' annotation
        run: 'echo "::warning::Java ${{ matrix.java-version }}, Gradle ${{ matrix.gradle-version }} | Docker CLI test build scan: ${{ steps.docker-cli.outputs.build-scan-url }}"'
        if: ${{ always() }}

      - name: Docker REST API test
        uses: gradle/gradle-build-action@v1
        id: docker-rest
        if: matrix.os != 'windows-latest'
        env:
          USE_DOCKER_REST: true
          CONTAINER_REGISTRY_IMAGE_PREFIX: ${{secrets.CONTAINER_REGISTRY_IMAGE_PREFIX}}
          CONTAINER_REGISTRY_SECRET: ${{secrets.CONTAINER_REGISTRY_SECRET}}
          CONTAINER_REGISTRY_URL: ${{secrets.CONTAINER_REGISTRY_URL}}
          CONTAINER_REGISTRY_USERNAME: ${{secrets.CONTAINER_REGISTRY_USERNAME}}
        with:
          arguments: dockerPush
          gradle-version: ${{ matrix.gradle-version }}
      - name: Publish 'Docker REST API' annotation
        run: 'echo "::warning::Java ${{ matrix.java-version }}, Gradle ${{ matrix.gradle-version }} | Docker REST API test build scan: ${{ steps.docker-rest.outputs.build-scan-url }}"'
        if: matrix.os != 'windows-latest'

      # liquibase tests
      - name: Liquibase test
        uses: gradle/gradle-build-action@v1
        id: liquibase
        if: ${{ always() }}
        with:
          arguments: liquibaseUpdate
          gradle-version: ${{ matrix.gradle-version }}
      - name: Publish Liquibase annotation
        run: 'echo "::warning::Java ${{ matrix.java-version }}, Gradle ${{ matrix.gradle-version }} | Liquibase test build scan: ${{ steps.liquibase.outputs.build-scan-url }}"'
        if: ${{ always() }}

      # terraform tests
      - name: Terraform test
        uses: gradle/gradle-build-action@v1
        if: ${{ always() }}
        id: terraform
        with:
          arguments: terraformMainInit
          gradle-version: ${{ matrix.gradle-version }}
      - name: Publish Terraform annotation
        run: 'echo "::warning::Java ${{ matrix.java-version }}, Gradle ${{ matrix.gradle-version }} | Terraform test build scan: ${{ steps.terraform.outputs.build-scan-url }}"'
        if: ${{ always() }}
